### ISSUE TITLE
User Returning Null

### ISSUE THREAD

**Issue by Aliman999** [Dymerz/RSI-Scraper#1]
Dewderonomy 

- https://mobitracker.co/Dewderonomy 
- https://robertsspaceindustries.com/citizens/Dewderonomy

**Comment by Dymerz** [comment]
Hi, can you provide further information about your problem such as:
- what goes wrong
- code causing the bug
- stack trace (if any)

**Comment by Aliman999** [comment]
The API started returning this user normally again. Closing the ticket.
